"""added one column to users table

Revision ID: 2d0ed83dd14
Revises: 
Create Date: 2017-08-12 17:59:37.498839

"""

# revision identifiers, used by Alembic.
revision = '2d0ed83dd14'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
