"""added one column to posts table

Revision ID: 301e9f1f51c
Revises: 562cb0d068a
Create Date: 2017-08-29 17:11:56.248223

"""

# revision identifiers, used by Alembic.
revision = '301e9f1f51c'
down_revision = '562cb0d068a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
