"""added one column to users table

Revision ID: 30f6c519b12
Revises: 2d0ed83dd14
Create Date: 2017-08-17 15:38:20.976787

"""

# revision identifiers, used by Alembic.
revision = '30f6c519b12'
down_revision = '2d0ed83dd14'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('imgpath', sa.String(length=100), server_default='default.jpg', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'imgpath')
    ### end Alembic commands ###
