"""added one column to users table

Revision ID: 3cf68a028c6
Revises: 30f6c519b12
Create Date: 2017-08-17 17:17:17.487270

"""

# revision identifiers, used by Alembic.
revision = '3cf68a028c6'
down_revision = '30f6c519b12'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    ### end Alembic commands ###
